{{ if (eq .Values.guac.graphqlServer.backend "arango") -}}

apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: {{ .Values.guac.arangoDb.name }}
spec:
  externalAccess:
    type: None
  auth:
    jwtSecretName: None
  tls:
    caSecretName: None
  {{- if .Values.guac.arangoDb.image.digest }}
  image: "{{ .Values.guac.arangoDb.image.repository }}@{{ .Values.guac.arangoDb.image.digest }}"
  {{- else }}
  image: "{{ .Values.guac.arangoDb.image.repository }}:{{ .Values.guac.arangoDb.image.tag | default .Chart.AppVersion}}"
  {{- end }}
  license:
    secretName: {{ .Values.guac.arangoDb.licenseSecret }}
  mode: {{ .Values.guac.arangoDb.mode }}
  environment: {{ .Values.guac.arangoDb.environment }}
  {{- with .Values.guac.arangoDb.single }}
  single:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.guac.arangoDb.agents }}
  agents:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.guac.arangoDb.dbservers }}
  dbservers:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.guac.arangoDb.coordinators }}
  coordinators:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
