# Copyright Kusari, Inc. and contributors
# Licensed under the MIT license. See LICENSE file in the project root for details.
{{ if .Values.guac.graphqlServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.guac.graphqlServer.name }}
{{- if .Values.guac.graphqlServer.annotations }}
  annotations:
{{ toYaml .Values.guac.graphqlServer.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
spec:
  replicas:  {{ .Values.guac.graphqlServer.replicas }}
  selector:
    matchLabels:
      {{- include "guac.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
      app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
  template:
    metadata:
      labels:
        {{- include "guac.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
        app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
    spec:
      containers:
      - name: {{ .Values.guac.graphqlServer.name }}
        {{- if .Values.guac.guacImage.digest }}
        image: "{{ .Values.guac.guacImage.repository }}@{{ .Values.guac.guacImage.digest }}"
        {{- else }}
        image: "{{ .Values.guac.guacImage.repository }}:{{ .Values.guac.guacImage.tag | default .Chart.AppVersion}}"
        {{- end }}
        imagePullPolicy: "{{ .Values.guac.guacImage.pullPolicy }}"
        command:
{{ toYaml .Values.guac.graphqlServer.image.command | indent 10 }}
        workingDir: {{ .Values.guac.guacImage.workingDir }}
{{- if .Values.guac.graphqlServer.ports }}
        ports:
{{ toYaml .Values.guac.graphqlServer.image.ports | indent 10 }}
{{- end }}
        volumeMounts:
          - name: guac-config
            mountPath: {{ .Values.guac.guacImage.workingDir }}
            readOnly: true
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      volumes:
        - name: guac-config
          configMap:
            name: guac-cm
      {{- with .Values.guac.graphqlServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.guac.graphqlServer.affinity }}
      affinity:
        {{- toYaml .Values.guac.graphqlServer.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.guac.graphqlServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}