# Copyright Kusari, Inc. and contributors
# Licensed under the MIT license. See LICENSE file in the project root for details.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guac-cm
data:
  guac.yaml: |

    # Nats setup
    nats-addr: nats://{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222

    # CSub setup
{{- with (index .Values.guac.collectSub.svcPorts 0) }}
    csub-addr: {{ $.Values.guac.collectSub.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .targetPort }}
    csub-listen-port: {{ .targetPort }}
{{- end }}

    # GQL setup
{{- with (index .Values.guac.graphqlServer.svcPorts 0) }}
    gql-backend: {{ $.Values.guac.graphqlServer.backend }}
    gql-listen-port: {{ .targetPort }}
    gql-debug: {{ $.Values.guac.graphqlServer.debug }}
    gql-test-data: false
    gql-addr: http://{{ $.Values.guac.graphqlServer.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .targetPort }}/query
{{- end }}
    
    # Collector behavior
    service-poll: true
    use-csub: true