{{- if .Values.guac.traefikIngress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}

  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Namespace }}.us.kusari.cloud
    external-dns.alpha.kubernetes.io/target: gateway.us.kusari.cloud
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    # traefik.ingress.kubernetes.io/router.middlewares: traefik-global-stripprefix@kubernetescrd,traefik-oathkeeper@kubernetescrd 

    # uncomment to enable forwardauth for this app at authentik
    # traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd 
    # traefik.ingress.kubernetes.io/router.middlewares: traefik-oathkeeper@kubernetescrd
    # traefik.ingress.kubernetes.io/router.priority: "10"
{{- if .Values.guac.traefikIngress.annotations }}
{{ toYaml .Values.guac.traefikIngress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
{{- range $key, $value := .Values.guac.traefikIngress.extraLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  {{- if .Values.guac.traefikIngress.ingressClassName }}
  ingressClassName: {{ .Values.guac.traefikIngress.ingressClassName }}
  {{- end }}
  # tls:
  # - hosts:
  #     - https-example.foo.com
  # - secretName: localhost-cert
  rules:
    # - host: {{ .Release.Namespace }}.{{ .Values.environment }}.{{ .Values.domain_name }}
    - host: {{ .Release.Namespace }}.us.kusari.cloud
      http: &http
        paths:
          - path: /playground
            pathType: Prefix
            backend:
              service:
                name: graphql-server
                port:
                  number: 8080
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: graphql-server
                port:
                  number: 8080
          - path: /
            # https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
            # pathType: Exact
            pathType: Prefix
            backend:
              service:
                name: visualizer
                port:
                  number: 3000
          {{ if .Values.guac.httpbin.enabled }}
          - path: /httpbin
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
          {{ end }}
          {{ if .Values.guac.webtop.enabled }}
          - path: /webtop
            pathType: Prefix
            backend:
              service:
                name: webtop
                port:
                  number: 3000
          {{ end }}
          {{ if .Values.guac.oauth2Proxy.enabled }}
          - path: /oauth
            pathType: Prefix
            backend:
              service: {{ .Release.Namespace }}-oauth2-proxy
                name: 
                port:
                  number: 80
          {{ end }}

    - host: {{ .Release.Namespace }}.api.us.kusari.cloud
      http:
        paths:
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: graphql-server
                port:
                  number: 8080
          {{ if .Values.guac.httpbin.enabled }}
          - path: /httpbin
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
          {{ end }}

{{- end -}}
